User.Microservice/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using User.Microservice.Data;
using User.Microservice.Data.Entieties;
using User.Microservice.Helpers.Security;
using User.Microservice.Helpers;
using User.Microservice.Models;
using User.Microservice.Repository.General;
using User.Microservice.ViewModel.Authorization;

namespace User.Microservice.Controllers
{
    public class AuthorizationController : BaseController
    {
        public RoleManager<IdentityRole> _roleManager;
       // public RoleManager<ApplicationRole> _roleManager;
       //rivate IFunctionRepository _functionRepository;
        public AuthorizationController(ApplicationDbContext context, PetTrackerContext db,
             RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager) : base(context,db, userManager)
        {
            _roleManager = roleManager;
           //functionRepository = functionRepository;
        }

        public IActionResult Index()
        {

            var roles = _roleManager.Roles.ToList();

            return View(roles);
        }

     [HttpGet]
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(IdentityRole model)
        {
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }
      /*  //metoda per me i shfaq menut
        //si parameter vjen roli i zgjedhur ne view index
        [HttpPost]
        public async Task<IActionResult> _Search(AuthorizationCreateViewModel model)
        {
            List<ListOfMenusAccess> lista = await _functionRepository.ListOfMenusAuthorized(model.Role);


            return PartialView(lista);
        }

        //Metoda perdoret per insertimin e qasjeve ne db
        //Nese ka qasje dhe access = false, i fshin qasjet
        //Nese nuk ka qasje dhe access = true i inserton
        [HttpPost]
        public async Task<IActionResult> ChangeAccess(string Role, string mide, string side, bool access)
        {
            if (string.IsNullOrEmpty(Role))
            {
                return Json(new ViewModel.ErrorViewModel
                {
                    ErrorNumber = ErrorStatus.Error,
                    ErrorDescription = "Te dhenat jo valide"
                });
            }

            //Dekriptimin e id-ve te menus dhe submenus
            int menuId = AesCrypto.Decrypt<int>(mide);
            int submenuId = AesCrypto.Decrypt<int>(side);

            Menu menu = null;
            Submenu subMenu = null;
            string claim = "", claimValue = "";

            //nese submenu ekziston
            if (submenuId != 0)
            {
                //gjejm submenu
                subMenu = await _db.Submenu.FindAsync(submenuId);

                //marrim claims te submenus
                claim = subMenu.Claim.Split(':')[0];
                claimValue = subMenu.Claim.Split(':')[1];
            }
            else
            {
                //gjejm menu
                menu = await _db.Menu.FindAsync(menuId);

                //marrim claims te menus
                claim = menu.Claim.Split(':')[0];
                claimValue = menu.Claim.Split(':')[1];
            }

            //gjejm rolin ne baze te parametrit Role
            ApplicationRole role = await _roleManager.FindByIdAsync(Role);

            //bejme check ne db tek tabela AspNetRoleClaims
            //nese ky rol i permban keto claims
            var hasClaims = _db.AspNetRoleClaims.Where(q => q.RoleId == role.Id &&
                                                       q.ClaimType == claim &&
                                                       q.ClaimValue == claimValue).Any();
            //Nese parametri access vlera e te cilit 
            //vjen nga view
            //Nese true dhe role nuk ka claims
            //I ben insert ne tabelen AspNetRoleClaims
            if (access && !hasClaims)
            {
                await _roleManager.AddClaimAsync(role, new Claim(claim, claimValue));
            }
            else // e kunderta, i fshin claims nga tabela AspNetRoleClaims per rolin e zgjedhur
            {
                await _roleManager.RemoveClaimAsync(role, new Claim(claim, claimValue));
            }

            ViewModel.ErrorViewModel error = new ViewModel.ErrorViewModel
            {
                Title = "Sukses",
                ErrorNumber = ErrorStatus.Success,
                ErrorDescription = "Te dhenat u ruajten me sukses"
            };

            return Json(error);
        }*/
    }
}

User.Microservice/Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using User.Microservice.Data;
using User.Microservice.Models;
using User.Microservice.Data.Entieties;

namespace User.Microservice.Controllers
{
    [Authorize(Roles ="user")]
    public class PetController : BaseController
    {
            
        public PetController(ApplicationDbContext context, PetTrackerContext db,UserManager<ApplicationUser> userManager) : base(context,db, userManager)
        {
        }

        public IActionResult Index()
        {
                  

            return View();
        }
    }
}

User.Microservice/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using User.Microservice.Data.Entieties;
using User.Microservice.Repository.General;
using User.Microservice.Models.Menu;
using User.Microservice.Models;
using Microsoft.EntityFrameworkCore;
using User.Microservice.Data;

namespace User.Microservice.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private IFunctionRepository _functionRepository;
        private ApplicationDbContext _context;
        //private UserManager<ApplicationUser> _userManager;
        //private RoleManager<ApplicationRole> _roleManager;

        public MenuViewComponent(IFunctionRepository functionRepository,
           ApplicationDbContext context)//userrManager<ApplicationUser> userManager,
            //RoleManager<ApplicationRole> roleManager)
        {
            _functionRepository = functionRepository;
            _context = context;
            //_userManager = userManager;
            //_roleManager = roleManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<ListOfMenus> menusTemp = new List<ListOfMenus>();

            //Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(UserClaimsPrincipal);

            //ApplicationUser user = await GetCurrentUserAsync();

            //var claims = await _userManager.GetClaimsAsync(user);
            //var roles = await _userManager.GetRolesAsync(user);

            //foreach (var item in roles)
            //{
            //    var role = await _roleManager.FindByNameAsync(item);
            //    var roleClaims = await _roleManager.GetClaimsAsync(role);

            //    var rolemenus = (await _functionRepository.GetListOfMenus(item)).Where(t => !menusTemp.Where(m => m.SubMenuController == t.SubMenuController).Any()).ToList();
            //    menusTemp.AddRange(rolemenus);
            //}

            List<MenuViewModel> menus = menusTemp.OrderBy(t => t.OrdinalNumberM).Select(t => new
            {
                Action = t.MenuAction,
                Area = t.MenuArea,
                Controller = t.MenuController,
                HasSub = t.HasSub,
                Icon = t.Icon,
                Name = t.MenuName,
                MenuId = t.MenuId,
                MenuStaysOpenFor = t.MenuStaysOpenFor
            }).Distinct().ToList()
                  .Select(t => new MenuViewModel
                  {
                      Action = t.Action,
                      Area = t.Area,
                      Controller = t.Controller,
                      HasSubMenu = t.HasSub,
                      Name = t.Name,
                      Icon = t.Icon,
                      StaysOpenFor = t.MenuStaysOpenFor,
                      Submenus = menusTemp.Where(s => s.MenuId == t.MenuId).OrderBy(t => t.OrdinalNumberS).Select(s => new SubmenuViewModel
                      {
                          SubMenuID = s.SubMenuId,
                          Action = s.SubMenuAction,
                          Area = s.SubMenuArea,
                          Controller = s.SubMenuController,
                          Name = s.SubMenuName,
                          Icon = s.SubIcon,
                          IsBlazor = s.IsBlazor,
                          ParentId = s.ParentId,
                          StaysOpenFor = s.SubMenuStaysOpenFor
                      }).Distinct().ToList()
                  }).ToList();

            return await Task.FromResult((IViewComponentResult)View("Sidebar", menus));
        }
    }
}

User.Microservice/Views/Shared/_Layout.cshtml
@{
    var user = (UserModel)ViewData["User"];
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - </title>
    @RenderSection("Styles", false)

    <!-- App css -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/metisMenu.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/simplebar.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/select2/select2.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/huebee/huebee.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/timepicker/bootstrap-material-datetimepicker.css" rel="stylesheet">
    <link href="~/lib/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
    <!-- Sweet Alert -->
    <link href="~/lib/sweet-alert2/sweetalert2.min.css" rel="stylesheet" type="text/css">
    <link href="~/lib/animate/animate.css" rel="stylesheet" type="text/css">
    <!-- DataTables -->
    <link href="~/lib/datatables/dataTables.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <link href="~/lib/datatables/buttons.bootstrap5.min.css" rel="stylesheet" type="text/css" />
    <!-- Responsive datatable examples -->
    <link href="~/lib/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="dark-sidenav">
    @if (User.IsInRole("Admin"))
            {
        @await Component.InvokeAsync("Menu")
        ;
        <div class="page-wrapper">
            <!-- Top Bar Start -->
        <div class="topbar">
            <!-- Navbar -->
            <nav class="navbar-custom">
                <ul class="list-unstyled topbar-nav float-end mb-0">
                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-bs-toggle="dropdown" href="#" role="button"
                           aria-haspopup="false" aria-expanded="false">
                            <span class="ms-1 nav-user-name hidden-sm"></span>
                                <span class="ms-1 nav-user-name hidden-sm">@user.FirstName @user.LastName</span>
                            <img src="~/images/users/user-5.jpg" alt="profile-user" class="rounded-circle thumb-xs" />
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a class="dropdown-item" href="#"><i data-feather="user" class="align-self-center icon-xs icon-dual me-1"></i> Profile</a>
                            <a class="dropdown-item" href="#"><i data-feather="settings" class="align-self-center icon-xs icon-dual me-1"></i> Settings</a>
                            <div class="dropdown-divider mb-0"></div>

                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index","Home")" method="post">
                                <button type="submit" class="dropdown-item"><i data-feather="power" class="align-self-center icon-xs icon-dual me-1"></i>Logout</button>
                            </form>
                        </div>
                    </li>
                </ul><!--end topbar-nav-->

                <ul class="list-unstyled topbar-nav mb-0">
                    <li>
                        <button class="nav-link button-menu-mobile">
                            <i data-feather="menu" class="align-self-center topbar-icon"></i>
                        </button>
                    </li>
                    <li class="creat-btn">
                        <div class="nav-link">
                            <a class=" btn btn-sm btn-soft-primary" href="#" role="button"><i class="fas fa-plus me-2"></i>New Pet</a>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- end navbar-->
        </div>
        <!-- Top Bar End -->
     
            @RenderBody()

        </div>
    }
    else
    {
         <div class="topbar">
                    <!-- Navbar -->
                    <nav class="navbar-custom">
                        <ul class="list-unstyled topbar-nav float-end mb-0">
                            
                            @*  <li class="nav-link">
                        <a class="nav-link text-darl" asp-controller="Authorization" asp-action="Index">Role </a>
                        </li>
                        <li class="nav-link">
                        <a class="nav-link text-darl" asp-controller="Pet" asp-action="Index">Pet </a>
                        </li>*@
                           

                            <li class="dropdown">
                                <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-bs-toggle="dropdown" href="#" role="button"
                               aria-haspopup="false" aria-expanded="false">
                                    <span class="ms-1 nav-user-name hidden-sm"></span>
                            <span class="ms-1 nav-user-name hidden-sm">@user.FirstName @user.LastName</span>
                                    <img src="~/images/users/user-5.jpg" alt="profile-user" class="rounded-circle thumb-xs" />
                                </a>
                                <div class="dropdown-menu dropdown-menu-end">
                                    <a class="dropdown-item" href="#"><i data-feather="user" class="align-self-center icon-xs icon-dual me-1"></i> Profile</a>
                                    <a class="dropdown-item" href="#"><i data-feather="settings" class="align-self-center icon-xs icon-dual me-1"></i> Settings</a>
                                    <div class="dropdown-divider mb-0"></div>

                                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index","Home")" method="post">
                                        <button type="submit" class="dropdown-item"><i data-feather="power" class="align-self-center icon-xs icon-dual me-1"></i>Logout</button>
                                    </form>
                                </div>
                            </li>
                        </ul><!--end topbar-nav-->

                        <ul class="list-unstyled topbar-nav mb-0">
                            <li class="creat-btn">
                                <div class="nav-link">
                                    <a class=" btn btn-sm btn-soft-primary" href="#" role="button"><i class="fas fa-plus me-2"></i>New Task</a>
                                </div>
                            </li>
                        </ul>
                    </nav>
            <!-- end navbar--> <h4 class="page-title">@ViewData["Title"]</h4>
                </div>
               
                @RenderBody()
            }


    <!-- jQuery  -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/metismenu.min.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/feather.min.js"></script>
    <script src="~/js/simplebar.min.js"></script>
    <script src="~/js/moment.js"></script>
    <script src="~/lib/daterangepicker/daterangepicker.js"></script>
    <script src="~/lib/idle-timer/idle-timer.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js" asp-append-version="true"></script>
    <script src="~/lib/select2/select2.min.js"></script>
    <script src="~/lib/huebee/huebee.pkgd.min.js"></script>
    <script src="~/lib/timepicker/bootstrap-material-datetimepicker.js"></script>
    <script src="~/lib/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
    <script src="~/lib/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js"></script>

    <!-- Sweet-Alert  -->
    <script src="~/lib/sweet-alert2/sweetalert2.min.js"></script>
    <script src="~/js/pages/jquery.sweet-alert.init.js"></script>

    <!-- Required datatable js -->
    <script src="~/lib/datatables/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/dataTables.bootstrap5.min.js"></script>

    <!-- Responsive examples -->
    <script src="~/lib/datatables/dataTables.responsive.min.js"></script>
    <script src="~/lib/datatables/responsive.bootstrap4.min.js"></script>
    <script src="~/js/pages/jquery.datatable.init.js"></script>
    <script src="~/js/pages/jquery.forms-advanced.js"></script>
    <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>

    <script src="~/js/app.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

User.Microservice/Views/Shared/_ModalPartial.cshtml
<div class="modal fade" id="modal-default" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal fade" id="modal-default-top" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>


<div class="modal fade bd-example-modal-lg" id="modal-large" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-xl" id="modal-x-large" tabindex="-1" role="dialog" style="display: none; z-index:9" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal fade bd-example-modal-sm" id="modal-small" tabindex="-1" role="dialog" style="display: none;z-index:1100" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal modal-left fade" id="modal-left" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal modal-fill fade" data-backdrop="false" id="modal-fill" tabindex="-1" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal modal-right fade" id="modal-right" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal center-modal fade" id="modal-center" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal center-modal fade bd-example-modal-lg" id="modal-center-large" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal center-modal fade bd-example-modal-lg" id="modal-center-xlarge" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal center-modal fade bd-example-modal-sm" id="modal-center-small" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>

<div class="modal center-modal fade modal-center" id="modal-small-calling" data-backdrop="static" data-keyboard="false" tabindex="-1" style="display: none; z-index:99999" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
        </div>
    </div>
</div>


<div class="modal fade" id="notification-modal" data-bs-backdrop="static" data-bs-keyboard="false" style="display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Notification</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-3 text-center align-self-center">
                        <div class="avatar-box thumb-xxl align-self-center me-2">
                            <span id="notification-bg" class="avatar-title rounded-circle"><i id="notification-icon" class=""></i></span>
                        </div>
                    </div><!--end col-->
                    <div class="col-lg-9">
                        <h5 id="notification-title"></h5>
                        <p id="notification-message" class="text-muted ms-2"></p>
                    </div><!--end col-->
                </div>
            </div>
        </div><!--end modal-content-->
    </div><!--end modal-dialog-->
</div><!--end modal-->